services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: lautaro
      POSTGRES_PASSWORD: jeankroos
      POSTGRES_DB: ecommerce_db
    ports:
      - 5434:5432
    networks:
      - ecommerce_network

networks:
  ecommerce_network:
    external: true
  
