services:
    e_commerce_app:
        build:
            context: ../e_comerce_app
            dockerfile: Dockerfile
        container_name: ecommerce_app
        ports:
            - 5000:5000
        networks:
            - ecommerce_network
        environment:
            - FLASK_CONTEXT=${FLASK_CONTEXT}
            - CATALOG_SERVICE_URL=${CATALOG_SERVICE_URL}
            - PAYMENT_SERVICE_URL=${PAYMENT_SERVICE_URL}
            - PURCHASE_SERVICE_URL=${PURCHASE_SERVICE_URL}
            - STOCK_SERVICE_URL=${STOCK_SERVICE_URL}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - REDIS_DB=${REDIS_DB}

    mscatalog:
        build:
            context: ../catalog_service
            dockerfile: Dockerfile
        container_name: mscatalog
        depends_on:
            - e_commerce_app
        ports:
            - 5001:5000
        networks:
            - ecommerce_network
        environment:
            - FLASK_CONTEXT=${FLASK_CONTEXT}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - REDIS_DB=${REDIS_DB}
            - TEST_DB_URI=${TEST_DB_URI}
            - DEV_DB_URI=${DEV_DB_URI}
            - PROD_DB_URI=${PROD_DB_URI}
    mspurchase:
        build:
            context: ../purchase_service
            dockerfile: Dockerfile
        container_name: mspurchase
        depends_on:
            - e_commerce_app
        ports:
            - 5002:5000
        networks:
            - ecommerce_network
        environment:
            - FLASK_CONTEXT=${FLASK_CONTEXT}
            - TEST_DB_URI=${TEST_DB_URI}
            - DEV_DB_URI=${DEV_DB_URI}
            - PROD_DB_URI=${PROD_DB_URI}
    mspayment:
        build:
            context: ../payment_service
            dockerfile: Dockerfile
        container_name: mspayment
        depends_on:
            - e_commerce_app
        ports:
            - 5003:5000
        networks:
            - ecommerce_network
        environment:
            - FLASK_CONTEXT=${FLASK_CONTEXT}
            - TEST_DB_URI=${TEST_DB_URI}
            - DEV_DB_URI=${DEV_DB_URI}
            - PROD_DB_URI=${PROD_DB_URI}
    msstock:
        build:
            context: ../stock_service
            dockerfile: Dockerfile
        container_name: msstock
        depends_on:
            - e_commerce_app
        ports:
            - 5004:5000
        networks:
            - ecommerce_network
        environment:
            - FLASK_CONTEXT=${FLASK_CONTEXT}
            - TEST_DB_URI=${TEST_DB_URI}
            - DEV_DB_URI=${DEV_DB_URI}
            - PROD_DB_URI=${PROD_DB_URI}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - REDIS_DB=${REDIS_DB}
networks:
    ecommerce_network:
        external: true
