services:
  ms-purchase:
      build:
        context: .
      container_name: purchase_service
      ports:
        - "5002:5000"
      networks:
        - ecommerce_network

networks:
  ecommerce_network:
    external: true