services:
  ms-stock:
      build:
        context: .
      container_name: stock_service
      ports:
        - "5004:5000"
      networks:
        - ecommerce_network

networks:
  ecommerce_network:
    external: true